---
version: "2"
checks:
  method-lines:
    config:
      threshold: 50
plugins:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
          count_threshold: 3
  eslint:
    enabled: true
    channel: "eslint-4"
    config: .eslintrc
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  radon:
    enabled: false
exclude_patterns:
- .circle.yml
- .storybook/
- .vscode/
- lib/
- config/
- public/
- node_modules/
- **/*.test.js
- stories/
