--- 
checks: 
  method-lines: 
    config: 
      threshold: 50
exclude_patterns: 
  - .babelrc
  - .eslintrc
  - .circle.yml
  - .storybook/
  - .vscode/
  - lib/
  - config/
  - public/
  - node_modules/
  - scripts/
  - "**/*.test.js"
  - "**/*.stories.js"
plugins: 
  csslint: 
    enabled: false
  duplication: 
    config: 
      languages: 
        javascript: 
          count_threshold: 3
          mass_threshold: 50
    enabled: true
  eslint: 
    channel: eslint-4
    config: .eslintrc
    enabled: true
  fixme: 
    enabled: true
  nodesecurity: 
    enabled: true
  radon: 
    enabled: false
version: "2"
